<?php
if ($page==='login') {
    page_header('Entrar'); ?><section class="card auth"><p class="eyebrow">BEM-VINDA, BEM-VINDO</p><h1>Seu espaço de apoio</h1><p>Entre para organizar sua rotina e participar.</p><?php form_open('login'); field('E-mail','email','email','',150,true); field('Senha','senha','password','',72,true); submit('Entrar'); ?><p><a href="<?=e(url('recuperar.php'))?>">Esqueci minha senha</a></p><p>Ainda não tem conta? <a href="<?=e(url('cadastro.php'))?>">Cadastre-se</a></p></section><?php
} elseif ($page==='cadastro') {
    page_header('Criar conta'); ?><section class="card auth"><h1>Vamos começar?</h1><p>Preencha seus dados. A senha deve ter ao menos 12 caracteres simples e no máximo 72 bytes.</p><?php form_open('signup'); field('Nome','nome','text','',100,true); field('Sobrenome','sobrenome','text','',100); field('E-mail','email','email','',150,true); field('Telefone (opcional)','telefone','tel','',20); field('Senha','senha','password','',72,true); field('Repita a senha','confirmar_senha','password','',72,true); ?><p><a href="<?=e(url('privacidade.php'))?>">Como tratamos seus dados</a></p><?php checkbox('Li as informações de privacidade e desejo criar minha conta.','privacidade',true); submit('Criar conta'); ?></section><?php
} elseif($page==='perfil' || $page==='pagperfil') {
    $u=require_user(false,false); page_header('Meu perfil'); ?><h1>Meu perfil</h1><div class="grid two"><section class="card"><img class="avatar" src="<?=e(image_url($u['foto_perfil']))?>" alt="Sua foto de perfil"><h2><?=e($u['nome'])?></h2><p><?=e($u['email'])?></p><p><?=$u['email_verificado']?'E-mail confirmado.':'E-mail ainda não confirmado.'?></p><?php if(!$u['email_verificado']):?><a class="button secondary" href="<?=e(url('verificar.php'))?>">Confirmar e-mail</a><?php endif; form_open('logout'); submit('Sair','secondary'); ?><details><summary>Exportar meus dados</summary><form method="post" action="<?=e(url('api/exportar.php'))?>"><?=csrf_field()?><?php field('Senha atual','senha_atual','password','',72,true); submit('Baixar meus dados','secondary'); ?></details><details><summary>Excluir minha conta</summary><p>A exclusão remove seus relatos, grupos criados, participações, agenda e sugestões salvas. Imagens externas entram na fila de exclusão. Cópias de segurança seguem a retenção informada na política.</p><?php form_open('delete'); field('Confirme sua senha atual','senha_atual','password','',72,true); checkbox('Entendo que esta exclusão é permanente.','confirmar_exclusao',true); submit('Excluir minha conta','danger'); ?></details></section><section class="card"><h2>Alterar dados</h2><?php form_open('profile',true); field('Nome','nome','text',$u['nome'],100,true); field('Sobrenome','sobrenome','text',$u['sobrenome'],100); field('E-mail','email','email',$u['email'],150,true); field('Telefone','telefone','tel',$u['telefone'],20); image_field('foto_perfil'); field('Senha atual (necessária para mudar e-mail ou senha)','senha_atual','password','',72); field('Nova senha (opcional)','senha','password','',72); field('Repita a nova senha','confirmar_senha','password','',72); submit('Salvar alterações'); ?></section></div><?php
} elseif($page==='recuperar') {
    page_header('Recuperar senha'); ?><section class="card auth"><h1>Recuperar acesso</h1><?php $token=$_GET['token'] ?? ''; if(is_string($token) && preg_match('/^[a-f0-9]{64}$/D',$token)): form_open('reset'); hidden('token',$token); field('Nova senha','senha','password','',72,true); field('Repita a senha','confirmar_senha','password','',72,true); submit('Redefinir senha'); else: ?><p>Envie seu e-mail para receber um link de redefinição.</p><?php form_open('reset_request'); field('E-mail','email','email','',150,true); submit('Enviar instruções'); endif; ?></section><?php
} elseif($page==='verificar') {
    page_header('Confirmar e-mail'); ?><section class="card auth"><h1>Confirme seu e-mail</h1><?php $token=$_GET['token'] ?? ''; if(is_string($token) && preg_match('/^[a-f0-9]{64}$/D',$token)): form_open('verify'); hidden('token',$token); submit('Confirmar meu e-mail'); elseif(current_user()): ?><p>Verifique sua caixa de entrada e spam. Você pode solicitar um novo link abaixo.</p><?php form_open('verify_request'); submit('Reenviar confirmação'); else: ?><p><a href="<?=e(url('login.php'))?>">Entre na sua conta</a> para solicitar uma confirmação.</p><?php endif; ?></section><?php
}
