<?php
$u=current_user(); $uid=(int)($u['id_usuario'] ?? 0);
$number=max(1,min(10000,(int)($_GET['pagina'] ?? 1))); $offset=($number-1)*12;
if($page==='cadastrar_grupo') {
    $u=require_user(); page_header('Criar grupo'); ?><section class="card auth"><h1>Crie um grupo de apoio</h1><p>O grupo será revisado antes da publicação. Você será identificado como responsável pela administração.</p><?php form_open('group',true); field('Nome do grupo','nome','text','',150,true); field('Foco','foco','text','',100); textarea_field('Apresente o grupo','mais_info',5000,true); field('Data do encontro','data_encontro','date','',10); field('Horário local','horario','time','',5); field('Link público do grupo','link','url','',2048); field('Contato público (opcional)','telefone_grupo','text','',150); image_field('imagem'); submit('Enviar para revisão'); ?></section><?php
} elseif($page==='grupos' || $page==='sobregrupos') {
    $rows=query("SELECT g.*, EXISTS(SELECT 1 FROM participantes p WHERE p.id_grupo=g.id_grupo AND p.id_usuario=?) AS participa FROM grupos g WHERE g.status='aprovado' OR g.id_criador=? ORDER BY g.id_grupo DESC LIMIT 13 OFFSET $offset",[$uid,$uid])->fetchAll();
    page_header('Grupos de apoio'); ?><div class="section-top"><div><p class="eyebrow">CONEXÕES QUE ACOLHEM</p><h1>Grupos de apoio</h1><p>Encontre um espaço para compartilhar e ouvir.</p></div><a class="button" href="<?=e(url('cadastrar_grupo.php'))?>">Criar grupo</a></div><div class="grid three"><?php foreach(array_slice($rows,0,12) as $g):?><article class="card"><img class="card-image" loading="lazy" src="<?=e(image_url($g['imagem']))?>" alt=""><span class="tag"><?=e($g['foco'] ?: 'Grupo de apoio')?></span><h2><?=e($g['nome_grupo'])?></h2><p class="preserve"><?=e($g['mais_info'])?></p><p><?=e($g['data_encontro'] ?? 'Data a combinar')?> <?=e(substr($g['horario'] ?? '',0,5))?></p><?php if($g['status']!=='aprovado'):?><p class="tag">Situação: <?=e($g['status'])?></p><?php endif; if($g['telefone_grupo']):?><p>Contato público: <?=e($g['telefone_grupo'])?></p><?php endif; try{$link=safe_link($g['link'] ?? '');}catch(DomainException $e){$link='';} if($link):?><a href="<?=e($link)?>" target="_blank" rel="noopener noreferrer">Abrir link do grupo ↗</a><?php endif; if($u && $g['status']==='aprovado'): form_open('join'); hidden('id',$g['id_grupo']); hidden('sair',$g['participa']?'1':'0'); submit($g['participa']?'Sair do grupo':'Participar'); endif; if($uid===(int)$g['id_criador']): form_open('delete_group'); hidden('id',$g['id_grupo']); submit('Excluir meu grupo','danger'); elseif($u && $g['status']==='aprovado'): report_form('grupo',(int)$g['id_grupo']); endif;?></article><?php endforeach;?></div><?php if(!$rows):?><div class="empty">Ainda não há grupos disponíveis. Você pode enviar o primeiro para revisão.</div><?php endif; pagination('grupos.php',$number,count($rows)>12);
} elseif($page==='relatos') {
    $rows=query("SELECT r.*,u.nome,u.foto_perfil FROM relatos r JOIN usuarios u ON u.id_usuario=r.id_usuario WHERE r.status='aprovado' OR r.id_usuario=? ORDER BY r.data_publicacao DESC,r.id_relato DESC LIMIT 13 OFFSET $offset",[$uid])->fetchAll();
    page_header('Relatos'); ?><p class="eyebrow">HISTÓRIAS E ESCUTA</p><h1>Você não está só</h1><p>Experiências pessoais não substituem orientações profissionais.</p><details class="card"><summary>Compartilhar um relato</summary><?php if($u): form_open('story'); field('Título','titulo','text','',150,true); textarea_field('Seu relato','conteudo',10000,true); checkbox('Ocultar meu nome e minha foto na publicação.','anonimo'); ?><p>Mesmo com autoria oculta, o relato permanece vinculado à sua conta para moderação e exclusão. Evite identificar outras pessoas ou publicar documentos de saúde.</p><?php checkbox('Entendo que o texto será público após aprovação e desejo publicá-lo.','publicacao',true); submit('Enviar para revisão'); else: ?><a href="<?=e(url('login.php'))?>">Entre para compartilhar.</a><?php endif; ?></details><div class="grid two"><?php foreach(array_slice($rows,0,12) as $r):?><article class="card"><p class="eyebrow"><?=$r['anonimo']?'Autoria oculta':e($r['nome'])?></p><h2><?=e($r['titulo'])?></h2><p class="preserve"><?=e($r['relato'])?></p><small><?=e(substr($r['data_publicacao'],0,10))?></small><?php if($r['status']!=='aprovado'):?><p>Situação: <?=e($r['status'])?></p><?php endif; if($uid===(int)$r['id_usuario']): form_open('delete_story'); hidden('id',$r['id_relato']); submit('Excluir meu relato','danger'); elseif($u): report_form('relato',(int)$r['id_relato']); endif;?></article><?php endforeach;?></div><?php if(!$rows):?><p class="empty">Ainda não há relatos publicados.</p><?php endif; pagination('relatos.php',$number,count($rows)>12);
} elseif($page==='admin') {
    require_admin(); page_header('Moderação'); ?><h1>Moderação</h1><p>Revise conteúdo, exposição de dados pessoais, links e alegações de saúde antes de aprovar. Os textos abaixo são enviados por usuários.</p><?php
    $more=false;
    foreach(['grupos'=>'grupo','relatos'=>'relato'] as $table=>$type) {
        $idcol=$type==='grupo'?'id_grupo':'id_relato';
        $rows=query("SELECT * FROM $table ORDER BY (status='pendente') DESC,$idcol DESC LIMIT 13 OFFSET $offset")->fetchAll();
        $more=$more || count($rows)>12;
        echo '<h2>'.e(ucfirst($table)).'</h2><div class="grid two">';
        foreach(array_slice($rows,0,12) as $r) { ?><article class="card"><h3><?=e($r['nome_grupo'] ?? $r['titulo'])?></h3><p class="preserve"><?=e($r['mais_info'] ?? $r['relato'])?></p><?php if($type==='grupo'):?><p>Link informado: <?=e($r['link'])?></p><p>Contato: <?=e($r['telefone_grupo'])?></p><?php endif;?><p>Situação: <?=e($r['status'])?> • Registro <?=e($r[$idcol])?></p><?php form_open('moderate'); hidden('tipo',$type); hidden('id',$r[$idcol]); ?><label>Decisão <select name="status"><option value="aprovado">Aprovar</option><option value="rejeitado">Rejeitar / ocultar</option><option value="pendente">Voltar para revisão</option></select></label><?php submit('Aplicar decisão'); ?></article><?php }
        echo '</div>';
    }
    $reports=query("SELECT * FROM denuncias WHERE resolvida=0 ORDER BY id DESC LIMIT 13 OFFSET $offset")->fetchAll(); ?><h2>Denúncias abertas</h2><?php foreach(array_slice($reports,0,12) as $r):?><article class="card"><p><?=e($r['tipo'])?> #<?=e($r['alvo'])?>: <?=e($r['motivo'])?></p><?php form_open('moderate'); hidden('tipo','denuncia'); hidden('id',$r['id']); hidden('status','resolvida'); submit('Marcar como analisada'); ?></article><?php endforeach; pagination('admin.php',$number,count($reports)>12 || $more);
}
function report_form(string $type,int $id): void { ?><details><summary>Denunciar conteúdo</summary><?php form_open('report'); hidden('tipo',$type); hidden('id',$id); textarea_field('Motivo','motivo',1000,true); submit('Enviar denúncia','secondary'); ?></details><?php }
