<?php
function page_header(string $title): void {
    $u=current_user();
    ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Vitalize: acolhimento, grupos de apoio e organização da sua rotina."><meta name="csrf-token" content="<?=e(csrf())?>"><title><?=e($title)?> — Vitalize</title><link rel="icon" href="<?=e(url('img/logov.png'))?>"><link rel="stylesheet" href="<?=e(url('css/style.css'))?>"><script src="<?=e(url('css/style.js'))?>" defer></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><a class="brand" href="<?=e(url('index.php'))?>"><img src="<?=e(url('img/logov.png'))?>" alt="" width="44" height="44">Vitalize</a><button class="menu-toggle secondary" aria-controls="menu" aria-expanded="false" type="button">Menu</button><nav id="menu" aria-label="Principal"><?php foreach(['index.php'=>'Início','grupos.php'=>'Grupos','doacao.php'=>'Doação','saude.php'=>'Minha rotina','relatos.php'=>'Relatos','sobre.php'=>'Sobre'] as $p=>$label):?><a href="<?=e(url($p))?>"><?=e($label)?></a><?php endforeach; ?><?php if($u && $u['tipo']==='admin'):?><a href="<?=e(url('admin.php'))?>">Moderação</a><?php endif;?><a class="button" href="<?=e(url($u?'pagperfil.php':'login.php'))?>"><?=$u?'Meu perfil':'Entrar'?></a></nav></header><main id="conteudo" tabindex="-1"><?php
    if (!empty($_SESSION['flash'])) { echo '<div class="notice" role="status">'.e($_SESSION['flash']).'</div>'; unset($_SESSION['flash']); }
}
function page_footer(): void { ?><footer><div><strong>Vitalize</strong><p>Acolhimento e apoio à sua rotina.</p></div><div><a href="<?=e(url('privacidade.php'))?>">Privacidade e seus dados</a><p>Projeto educacional. Não substitui atendimento profissional.</p><small>© <?=date('Y')?> Vitalize</small></div></footer></body></html><?php }
function form_open(string $action, bool $upload = false): void { ?><form method="post" action="<?=e(url('acao.php'))?>" <?=$upload?'enctype="multipart/form-data"':''?>><?=csrf_field()?><input type="hidden" name="acao" value="<?=e($action)?>"><?php }
function hidden(string $name,mixed $value): void { echo '<input type="hidden" name="'.e($name).'" value="'.e($value).'">'; }
function field(string $label,string $name,string $type='text',mixed $value='',int $max=150,bool $required=false): void {
    static $i=0; $id='f'.(++$i);
    ?><div class="field"><label for="<?=$id?>"><?=e($label)?></label><input id="<?=$id?>" type="<?=e($type)?>" name="<?=e($name)?>" value="<?=e($value)?>" maxlength="<?=$max?>" <?=$required?'required':''?> <?=$type==='password'?'autocomplete="new-password"':''?>></div><?php
}
function textarea_field(string $label,string $name,int $max,bool $required=false): void { static $i=0; $id='t'.(++$i); ?><div class="field"><label for="<?=$id?>"><?=e($label)?></label><textarea id="<?=$id?>" name="<?=e($name)?>" rows="4" maxlength="<?=$max?>" <?=$required?'required':''?>></textarea></div><?php }
function checkbox(string $label,string $name,bool $required=false): void { ?><label class="check"><input type="checkbox" name="<?=e($name)?>" value="1" <?=$required?'required':''?>> <span><?=e($label)?></span></label><?php }
function submit(string $label,string $class=''): void { echo '<button class="'.e($class).'" type="submit">'.e($label).'</button></form>'; }
function image_field(string $name): void { if(env('UPLOADS_ENABLED','0')==='1') { ?><div class="field"><label>Imagem (JPEG, PNG ou WebP, até 2 MB)<input type="file" name="<?=e($name)?>" accept="image/jpeg,image/png,image/webp"></label></div><?php } }
function pagination(string $page,int $number,bool $more): void { ?><nav class="pagination" aria-label="Paginação"><?php if($number>1):?><a class="button secondary" href="<?=e(url($page.'?pagina='.($number-1)))?>">Anterior</a><?php endif;?><span>Página <?=$number?></span><?php if($more):?><a class="button secondary" href="<?=e(url($page.'?pagina='.($number+1)))?>">Próxima</a><?php endif;?></nav><?php }
